name: seedswitch
version: '${version}'
main: com.imwoki.seedswitch.Seedswitch
api-version: '1.21.10'
load: POSTWORLD

commands:
  seedswitch:
    description: Управление автоматической сменой сида
    usage: /seedswitch <settimer <секунды>|off>